/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ottobite (https://sketchfab.com/ottobite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-hacked-pc-sketchfabweeklychallenge-192ab9d4706f4ffaaf22f9a299289d75
Title: Stylized Hacked PC #SketchfabWeeklyChallenge
*/

import { useGLTF } from '@react-three/drei'

const HackerRoom = (props) => {
  const { nodes, materials } = useGLTF('/models/scene.glb')
  return (
    <group {...props} dispose={null}> {/* Apply transformations from props */}
    <mesh
      geometry={nodes.Final_lambert1_0.geometry}
      material={materials.lambert1}
    />
  </group>
  )
};

export default HackerRoom;

useGLTF.preload('/models/scene.glb')